In [118]:
import random
import numpy as np

positions = [[0,0], [0,1], [1,0], [1,1]]
positions = np.array(positions)
values = [1.0,2.0,3.0,4.0]

def distance(x,y):
    x = np.linalg.norm(positions[x] - positions[y], ord=2)
    return np.abs(x)

def sample():
    x0 = random.choice(range(4))
#     x0 = 


transisition_mat = np.zeros((4,4))

for x in range(4):
    z = 0.0
    max_z = 0
    for y in range(4):
        if x == y:
            continue
        n = distance(x,y)        
        max_z = max(n, max_z)
        
    for y in range(4):
        if x == y:
            continue    
        n = distance(x,y)        
        z += (max_z-distance(x,y) + 1)
        
    for y in range(4):
        if x == y:
            continue
        transisition_mat[x,y] = (max_z-distance(x,y) + 1)/z
    

value_ratio_mat = np.zeros((4,4))

for x in range(4):
    for y in range(4):
        k  = values[y] / values[x] 
        k = min(k,1.0)
        value_mat[x,y] = k
        


In [119]:
transisition_mat

array([[ 0.        ,  0.36939806,  0.36939806,  0.26120387],
       [ 0.36939806,  0.        ,  0.26120387,  0.36939806],
       [ 0.36939806,  0.26120387,  0.        ,  0.36939806],
       [ 0.26120387,  0.36939806,  0.36939806,  0.        ]])

In [120]:
value_mat

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.5       ,  1.        ,  1.        ,  1.        ],
       [ 0.33333333,  0.66666667,  1.        ,  1.        ],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ]])

In [121]:
rw_mat = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        rw_mat[i,j] = transisition_mat[i,j] * value_mat[i,j]

In [122]:
rw_mat_row_sum = np.sum(rw_mat, axis=1)

In [123]:
for i in range(4):
    rw_mat[i,i] = 1-rw_mat_row_sum[i]

In [124]:
rw_mat

array([[ 0.        ,  0.36939806,  0.36939806,  0.26120387],
       [ 0.18469903,  0.18469903,  0.26120387,  0.36939806],
       [ 0.12313269,  0.17413592,  0.33333333,  0.36939806],
       [ 0.06530097,  0.18469903,  0.27704855,  0.47295145]])

In [125]:
init_dist = np.random.rand(4)
init_dist = init_dist / np.sum(init_dist)

In [126]:
init_dist = np.matrix(init_dist)
rw_mat = np.matrix(rw_mat)
for i in range(1000):
    wdist = init_dist * rw_mat

In [127]:
init_dist * rw_mat

matrix([[ 0.10250105,  0.23115505,  0.30171165,  0.36463224]])

In [128]:
wdist

matrix([[ 0.10250105,  0.23115505,  0.30171165,  0.36463224]])

In [140]:
rw_mat*np.linalg.eig(rw_mat.T)[1][:,0]

matrix([[ 0.52796909],
        [ 0.51400128],
        [ 0.53841068],
        [ 0.57650547]])

In [173]:
from numpy.random import choice
from collections import defaultdict
init_dist = np.random.rand(4)
init_dist = init_dist / np.sum(init_dist)
init_dist = np.matrix(init_dist)

def sample():
    dist = defaultdict(float)
    total = 1000
    for _ in range(total):
        x_curr = choice(range(0,4), p=init_dist.tolist()[0])
        for j in range(100):
            x_curr = choice(range(0,4), p=rw_mat[x_curr].tolist()[0])
        dist[x_curr] += 1.0
    for k in dist:
        dist[k] = dist[k]/total
    return dist

In [174]:
sample()

defaultdict(float, {0: 0.105, 1: 0.191, 2: 0.302, 3: 0.402})

In [175]:
rw_mat

matrix([[ 0.        ,  0.36939806,  0.36939806,  0.26120387],
        [ 0.18469903,  0.18469903,  0.26120387,  0.36939806],
        [ 0.12313269,  0.17413592,  0.33333333,  0.36939806],
        [ 0.06530097,  0.18469903,  0.27704855,  0.47295145]])

In [159]:
rw_mat[0]

matrix([[ 0.        ,  0.36939806,  0.36939806,  0.26120387]])

In [1]:
import polylearn